### ISSUE TITLE
65주차 알고리즘 문제 풀이

### ISSUE THREAD

**Issue by kinglim00** [b1urrrr/Algorithm-Study#593]
- 기간 : 2023.10.09. ~ 2023.10.15.
- 문제 개수 : 3개

**Comment by kinglim00** [comment]
이코테 구현(완전탐색, 시뮬레이션) 파트도 복습 겸 다시 풀었는데 파일에 있어서 따로 올리진 않았습니다!

**Comment by LGAIN** [comment]
오 복습 좋아요 이번주도 고생하셨습니다! 👍
